version: "3.3"

services:
  fastapi:
    build: .
    command: uvicorn main:app --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3308:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : "root"
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
